// Code generated by 'micro gen' command.
// DO NOT EDIT!

package args

import (
	"github.com/chiachan163/cc-orm/model/mongo"
	"github.com/henrylee2cn/erpc/v6/codec"
)

// EmptyStruct alias of type struct {}
type EmptyStruct = codec.PbEmpty

// User user info
type User struct {
	Id        int64  `key:"pri" json:"id"`
	Name      string `key:"uni" json:"name"`
	Age       int32  `json:"age"`
	UpdatedAt int64  `json:"updated_at"`
	CreatedAt int64  `json:"created_at"`
	DeletedTs int64  `json:"deleted_ts"`
}

// Meta comment...
type Meta struct {
	Id        mongo.ObjectId `key:"pri" bson:"_id" json:"_id"`
	Uid       int64          `key:"uni" bson:"uid" json:"uid"`
	Hobby     []string       `bson:"hobby" json:"hobby"`
	Tags      []string       `bson:"tags" json:"tags"`
	UpdatedAt int64          `json:"updated_at" bson:"updated_at"`
	CreatedAt int64          `json:"created_at" bson:"created_at"`
	DeletedTs int64          `json:"deleted_ts" bson:"deleted_ts"`
}
